environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

    # Cache dependencies
    # pypi.coldfix.de/simple serves prebuilt .whl archives that were
    # downloaded from: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml
    PIP_FIND_LINKS: "file://C:\\pip-cache http://pypi.coldfix.de/simple"
    PIP_WHEEL_DIR:  C:\pip-cache

    MADX_DIR:       C:\madx
    MINGW_HOME:     C:\mingw-static

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

install:
  # Log initial environment variables and cache contents
  - "set"
  - ps: "if (Test-Path $env:PIP_WHEEL_DIR) { ls $env:PIP_WHEEL_DIR }"
  - ps: "if (Test-Path $env:MINGW_HOME)    { ls $env:MINGW_HOME }"

  # Add python and installed scripts to PATH
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install 'wheel' package which is needed for the following step
  - "pip install wheel"

  # rebuild dependency cache (if not existing) and then install
  # dependencies from cache:
  # The numpy .whl seems to be recognized as a pre-release, which is why --pre
  # is needed to make pip use the file anyways:
  - "pip wheel --no-index --pre cython numpy pyyaml"
  - "pip wheel setuptools coverage coveralls"
  - "pip install --no-index --pre cython numpy pyyaml setuptools coverage coveralls"

  # Install the build environment with a script that uses the environment
  # variables: we use a Python 3.4 to run the script as it needs to uncompress
  # .tar.xv archives which is not supported in Python 2.
  - "set PYTHON_HOME=%PYTHON%"
  - "set ARCH=%PYTHON_ARCH%"
  - "C:\\Python34-x64\\python appveyor\\pywinbuilder.py"
  - "set PATH=%MINGW_HOME%\\bin;%PATH%"

  # build MAD-X
  - "call appveyor\\get_madx.bat %MADX_DIR%"

  # build and install cpymad
  - "python setup.py build_ext -c mingw32 -lquadmath --madxdir=%MADX_DIR%"
  - "python setup.py bdist_wheel"
  # wildcard expansion is a pain in CMD.exe and just a little less in
  # powershell:
  - ps: "pip install (ls dist\\* | % {\"$_\"})"

  # prevent python from accidentally importing the cpymad package from the
  # local check-out - we want the installed package, as only it contains the
  # libmadx.pyd binary:
  - "rd /s /q cpymad"

  # Log final environment variables and cache contents
  - "set"
  - ps: "ls $env:PIP_WHEEL_DIR"
  - ps: "ls $env:MINGW_HOME"

build: off

test_script:
  - coverage run --source=cpymad    test/test_resource.py -v
  - coverage run --source=cpymad -a test/test_rpc.py      -v
  - coverage run --source=cpymad -a test/test_util.py     -v
  - coverage run --source=cpymad -a test/test_madx.py     -v
  - coverage run --source=cpymad -a test/test_locator.py  -v
  - coverage run --source=cpymad -a test/test_model.py    -v

after_test:
 - coveralls

artifacts:
  - path: dist\*

cache:
  - C:\pip-cache
  - C:\mingw-static
